module.exports =  diasLaborales = {
    lunes:{
    hora_24 : false,
    hora_23: false,
    hora_22 : false,
    hora_21 : false,
    hora_20 : false,
    hora_19 : false,
    hora_18 : false,
    hora_17 : false,
    hora_16 : false,
    hora_15 : false,
    hora_14 : false,
    hora_13 : false,
    hora_12 : false,
    hora_11 : false,
    hora_10 : false,
    hora_09 : false,
    hora_08 : false,
    hora_07 : false,
    hora_06 : false,
    hora_05 : false,
    hora_04 : false,
    hora_03 : false,
    hora_02 : false,
    hora_01 : false,
    hora_00 : false,
    },
    martes:{
        hora_24 : false,
        hora_23: false,
        hora_22 : false,
        hora_21 : false,
        hora_20 : false,
        hora_19 : false,
        hora_18 : false,
        hora_17 : false,
        hora_16 : false,
        hora_15 : false,
        hora_14 : false,
        hora_13 : false,
        hora_12 : false,
        hora_11 : false,
        hora_10 : false,
        hora_09 : false,
        hora_08 : false,
        hora_07 : false,
        hora_06 : false,
        hora_05 : false,
        hora_04 : false,
        hora_03 : false,
        hora_02 : false,
        hora_01 : false,
        hora_00 : false,
        },
    miercoles:{
    hora_24 : false,
    hora_23: false,
    hora_22 : false,
    hora_21 : false,
    hora_20 : false,
    hora_19 : false,
    hora_18 : false,
    hora_17 : false,
    hora_16 : false,
    hora_15 : false,
    hora_14 : false,
    hora_13 : false,
    hora_12 : false,
    hora_11 : false,
    hora_10 : false,
    hora_09 : false,
    hora_08 : false,
    hora_07 : false,
    hora_06 : false,
    hora_05 : false,
    hora_04 : false,
    hora_03 : false,
    hora_02 : false,
    hora_01 : false,
    hora_00 : false,
    },
    jueves:{
    hora_24 : false,
    hora_23: false,
    hora_22 : false,
    hora_21 : false,
    hora_20 : false,
    hora_19 : false,
    hora_18 : false,
    hora_17 : false,
    hora_16 : false,
    hora_15 : false,
    hora_14 : false,
    hora_13 : false,
    hora_12 : false,
    hora_11 : false,
    hora_10 : false,
    hora_09 : false,
    hora_08 : false,
    hora_07 : false,
    hora_06 : false,
    hora_05 : false,
    hora_04 : false,
    hora_03 : false,
    hora_02 : false,
    hora_01 : false,
    hora_00 : false,
    },
    viernes:{
    hora_24 : false,
    hora_23: false,
    hora_22 : false,
    hora_21 : false,
    hora_20 : false,
    hora_19 : false,
    hora_18 : false,
    hora_17 : false,
    hora_16 : false,
    hora_15 : false,
    hora_14 : false,
    hora_13 : false,
    hora_12 : false,
    hora_11 : false,
    hora_10 : false,
    hora_09 : false,
    hora_08 : false,
    hora_07 : false,
    hora_06 : false,
    hora_05 : false,
    hora_04 : false,
    hora_03 : false,
    hora_02 : false,
    hora_01 : false,
    hora_00 : false,
    },
    sabado:{
    hora_24 : false,
    hora_23: false,
    hora_22 : false,
    hora_21 : false,
    hora_20 : false,
    hora_19 : false,
    hora_18 : false,
    hora_17 : false,
    hora_16 : false,
    hora_15 : false,
    hora_14 : false,
    hora_13 : false,
    hora_12 : false,
    hora_11 : false,
    hora_10 : false,
    hora_09 : false,
    hora_08 : false,
    hora_07 : false,
    hora_06 : false,
    hora_05 : false,
    hora_04 : false,
    hora_03 : false,
    hora_02 : false,
    hora_01 : false,
    hora_00 : false,
    },
    domingo:{
    hora_24 : false,
    hora_23: false,
    hora_22 : false,
    hora_21 : false,
    hora_20 : false,
    hora_19 : false,
    hora_18 : false,
    hora_17 : false,
    hora_16 : false,
    hora_15 : false,
    hora_14 : false,
    hora_13 : false,
    hora_12 : false,
    hora_11 : false,
    hora_10 : false,
    hora_09 : false,
    hora_08 : false,
    hora_07 : false,
    hora_06 : false,
    hora_05 : false,
    hora_04 : false,
    hora_03 : false,
    hora_02 : false,
    hora_01 : false,
    hora_00 : false,
    }
}